language: cpp
dist: bionic

compiler:
- gcc

os:
- linux

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic-rc main'
    packages:
      - gcc-10
      - g++-10
      - ninja-build
      - libbfd-dev

install:
  sudo apt-get install snapd;
  sudo snap install cmake --beta --classic;

script:
  - export CC=gcc-10
  - export CXX=g++-10
  - /snap/cmake/current/bin/cmake --version
  - /snap/cmake/current/bin/cmake CMakeLists.txt
  - /snap/cmake/current/bin/cmake  --build . --target install
